### ISSUE TITLE
refactor discussion controller to update discussion so it returns newly updated data

### ISSUE THREAD

**Issue by struckchure** [Dev-47/unigram-forum-service#17]

**Comment by Horlakz** [comment]
isn't this suppose to be done in the frontend
re fetching data??

**Comment by Horlakz** [comment]
@Horlakz No reply?

**Comment by struckchure** [comment]
when a data is updated, it needs to return the new data that includes the update

**Comment by Horlakz** [comment]
@struckchure Ohh I get you now, alright

**Comment by Horlakz** [comment]
close this issue na
