### ISSUE TITLE
fix GET request for the discussion reply returning 'not found'

### ISSUE THREAD

**Issue by Horlakz** [Dev-47/unigram-forum-service#45]
json request response
![image](https://user-images.githubusercontent.com/79817415/168045590-fe995ea1-f5e5-4a76-a11b-4f8dd3a81e94.png)

server error
![image](https://user-images.githubusercontent.com/79817415/168045686-3e395558-de66-450c-ab3e-e679f2af0e27.png)

**Comment by struckchure** [comment]
you tried to get a reply and you got a 404, that's not an error :man_shrugging:

**Comment by struckchure** [comment]
and also, the id you pass should be id of the content, not the reply itself

![Screenshot 2022-05-12 at 11-05-28 Issues · Dev-47_unigram-forum-service](https://user-images.githubusercontent.com/55154055/168046618-dad1afa2-29fe-4ac8-b502-16ecc69f6ef9.png)

**Comment by Horlakz** [comment]
@struckchure I passed content ID, same thing

Do
js
find({ content_id: content_id })

**Comment by struckchure** [comment]
@Horlakz then the reply doesn't exist

**Comment by Horlakz** [comment]
@struckchure Does it work on your end? With that code?

**Comment by Horlakz** [comment]
> @Horlakz then the reply doesn't exist
> 
> did you create a reply

yes I created a reply
```js
find({ content_id: content_id })
```

works now with that..
